# Generated by Django 3.1.3 on 2021-09-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmaster',
            name='account_no',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
