# Generated by Django 3.1.3 on 2021-09-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210917_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmaster',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='accountmaster',
            name='edited_on',
        ),
    ]
