# Generated by Django 3.1.3 on 2021-09-17 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20210917_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PD_Intial',
            new_name='PD_Initial',
        ),
    ]
