# Generated by Django 3.1.3 on 2021-09-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210917_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmaster',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='pd_final',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pd_initial',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pd_report',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
