# Generated by Django 3.1.3 on 2021-09-18 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210917_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd_initial',
            name='account_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accountmaster'),
        ),
    ]
