# Generated by Django 3.1.3 on 2021-09-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210918_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='pd_initial',
            name='account_no_temp',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
