# Generated by Django 3.1.3 on 2021-09-22 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_pd_initial_account_no_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pd_report',
            name='account_type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pd_report',
            name='cin',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pd_report',
            name='product_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pd_report',
            name='sectors',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pd_report',
            name='zscore',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LGD_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('cin', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('sectors', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ead_os', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pv_cashflows', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pv_cost', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('beta_value', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('sec_flag', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('factor_4', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('factor_5', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_1', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_3', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_4', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_5', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('mgmt_overlay_1', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('mgmt_overlay_2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('rec_rate', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('est_rr', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('est_lgd', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('final_lgd', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('account_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accountmaster')),
            ],
        ),
        migrations.CreateModel(
            name='LGD_Initial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('account_no_temp', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ead_os', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pv_cashflows', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pv_cost', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('beta_value', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('sec_flag', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('factor_4', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('factor_5', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_1', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_3', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_4', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_5', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('mgmt_overlay_1', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('mgmt_overlay_2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('file_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('edited_on', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('account_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accountmaster')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LGD_Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('ead_os', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pv_cashflows', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pv_cost', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('beta_value', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('sec_flag', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('factor_4', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('factor_5', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_1', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_3', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_4', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('avg_5', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('mgmt_overlay_1', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('mgmt_overlay_2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('file_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accountmaster')),
            ],
        ),
    ]
