# Generated by Django 3.1.3 on 2021-09-26 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_stage_final_stage_initial_stage_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='EIR_Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('account_type', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('sectors', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('cin', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('loan_availed', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('cost_avail', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('rate', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('emi', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('os_principal', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('os_interest', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('fair_value', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('coupon', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('discount_factor', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('col_1', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('col_2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('col_3', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accountmaster')),
            ],
        ),
        migrations.CreateModel(
            name='EIR_Initial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('account_no_temp', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('loan_availed', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('cost_avail', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('rate', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('emi', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('os_principal', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('os_interest', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('fair_value', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('coupon', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('discount_factor', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('col_1', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('col_2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('col_3', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('file_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('edited_on', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('account_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accountmaster')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EIR_Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('period', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('loan_availed', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('cost_avail', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('rate', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('emi', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('os_principal', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('os_interest', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('fair_value', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('coupon', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('discount_factor', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('col_1', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('col_2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('col_3', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accountmaster')),
            ],
        ),
    ]
