# Generated by Django 3.1.3 on 2021-09-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_eir_final_eir_initial_eir_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMissing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no_temp', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('file_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
