# Generated by Django 3.1.3 on 2021-09-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_accountmissing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmissing',
            old_name='account_no_temp',
            new_name='account_no',
        ),
    ]
