# Generated by Django 3.1.3 on 2021-09-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210926_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='lgd_final',
            name='rec_rate',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lgd_initial',
            name='rec_rate',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
