# Generated by Django 3.1.3 on 2021-09-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210928_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lgd_final',
            name='rec_rate',
        ),
        migrations.RemoveField(
            model_name='lgd_initial',
            name='rec_rate',
        ),
    ]
