# Generated by Django 3.1.3 on 2021-09-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210928_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='lgd_report',
            name='account_type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
