# Generated by Django 3.1.3 on 2021-10-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_lgd_report_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage_report',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='stage_report',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='stage_report',
            name='edited_on',
        ),
        migrations.RemoveField(
            model_name='stage_report',
            name='file_identifier',
        ),
    ]
