# Generated by Django 3.1.3 on 2021-10-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211010_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=250)),
                ('first_name', models.TextField(db_index=True, max_length=250)),
                ('last_name', models.TextField(db_index=True, max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('email_sent_on', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
    ]
