# Generated by Django 3.1.3 on 2021-10-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='status',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
