# Generated by Django 3.1.3 on 2021-10-30 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_new_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Mange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, choices=[('Master', 'Master'), ('user', 'User'), ('PD Initial', 'PD Initial'), ('LGD Initial', 'LGD Initial'), ('Stage Initial', 'Stage Initial'), ('EIR Initial', 'EIR Initial'), ('ECL Initial', 'ECL Initial'), ('PD Final', 'PD Final'), ('LGD Final', 'LGD Final'), ('Stage Final', 'Stage Final'), ('EIR Final', 'EIR Final'), ('ECL Final', 'ECL Final'), ('PD Report', 'PD Report'), ('LGD Final', 'LGD Report'), ('Stage Report', 'Stage Report'), ('EIR Report', 'EIR Report'), ('ECL Report', 'ECL Report')], db_index=True, max_length=255, null=True)),
                ('process_name', models.CharField(blank=True, choices=[('F', 'Full'), ('R', 'Range')], db_index=True, max_length=1, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_range_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_range_date', models.DateField(blank=True, db_index=True, null=True)),
                ('total_deleted', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
